version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      DB_HOST: mongo
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
    - 3000:80
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: chat
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
volumes:
  mongodb_data: